# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "36c79003824b6f0ebbdfbea2ec97241e"
name = "myapptest11UdemyOne"
handle = "myapptest11UdemyOne"
application_url = "https://acc-systems-mh-hope.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hdlm2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://acc-systems-mh-hope.trycloudflare.com/auth/callback",
  "https://acc-systems-mh-hope.trycloudflare.com/auth/shopify/callback",
  "https://acc-systems-mh-hope.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
